import http.server
import json
import socketserver

import cv2
from urllib.parse import urlparse
from urllib.parse import parse_qs
from functools import cached_property
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qsl, urlparse

from requests_toolbelt.multipart import decoder
import numpy as np

HTML_TEXT='''
<!DOCTYPE html> 
<html> 

<head>
    <title>Hello World!</title>
</head>

<body>
    <h1 style=\"color:green;\">GeeksforGeeks</h1>
    <form method="post" enctype="multipart/form-data">
        <label for="imageUpload">Choose an image to upload:</label>
        <input type="file" id="imageUpload" name="image" accept="image/*">
        <input type="submit" value="Upload Image">
    </form>
</body>

</html>
'''

class WebRequestHandler(BaseHTTPRequestHandler):
    @cached_property
    def url(self):
        return urlparse(self.path)

    @cached_property
    def query_data(self):
        return dict(parse_qsl(self.url.query))

    @cached_property
    def post_data(self):
        content_length = int(self.headers.get("Content-Length", 0))
        return self.rfile.read(content_length)

    @cached_property
    def form_data(self):
        return dict(parse_qsl(self.post_data.decode("utf-8")))

    @cached_property
    def cookies(self):
        return SimpleCookie(self.headers.get("Cookie"))

    def do_GET(self):
        print("get received")
        self.send_response(200)
        #self.send_header("Content-Type", "application/json")
        self.send_header("Content-type", "text/html")
        self.end_headers()

        #self.wfile.write(self.get_response().encode("utf-8"))
        # Some custom HTML code, possibly generated by another function
        html = HTML_TEXT

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))
        query_components = parse_qs(urlparse(self.path).query)
        if query_components.get('image'):
            freq = query_components.get('image')  # <--- do whatever you want with that value
            print(freq)

        self._set_response(200)
        self.wfile.write("Python HTTP server received your GET request".encode("utf-8"))


    def do_POST(self):
        #very basic system. http get is the html start up page
        #http post is when the user upload a file

        self.send_response(200)
        #self.send_header("Content-Type", "application/json")
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.path = '/upload'
        content_length = int(self.headers['Content-Length'])

        # get data content bytes
        file_content = self.rfile.read(content_length)

        # Use multipart parser to strip boundary
        multipart_data = decoder.MultipartDecoder(file_content, self.headers['Content-Type']).parts
        image_byte = multipart_data[0].content
        # Read image using cv2
        image_numpy = np.frombuffer(image_byte, np.int8)
        img = cv2.imdecode(image_numpy, cv2.IMREAD_UNCHANGED)
        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body><h1>image {content_length} bytes received </h1></body></html>"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        self._set_response(200)

    def get_response(self):
        return json.dumps(
            {
                "path": self.url.path,
                "query_data": self.query_data,
                "post_data": self.post_data.decode("utf-8"),
                "form_data": self.form_data,
                "cookies": {
                    name: cookie.value
                    for name, cookie in self.cookies.items()
                },
            }
        )


class MyHttpRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Sending an '200 OK' response
        self.send_response(200)

        # Setting the header
        self.send_header("Content-type", "text/html")

        # Whenever using 'send_header', you also have to call 'end_headers'
        self.end_headers()

        # Extract query param
        name = 'dub'
        query_components = parse_qs(urlparse(self.path).query)
        if 'name' in query_components:
            name = query_components["name"][0]

        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body><h1>Hello {name}!</h1></body></html>"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

        return



# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    # Create an object of the above class
    #handler_object = MyHttpRequestHandler
    handler_object = WebRequestHandler
    PORT = 8002
    my_server = socketserver.TCPServer(("", PORT), handler_object)

    # Star the server
    my_server.serve_forever()

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
