import http.server
import json
import socketserver
import logging
import cv2
from urllib.parse import urlparse
from urllib.parse import parse_qs
from functools import cached_property
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qsl, urlparse

from requests_toolbelt.multipart import decoder
import numpy as np

HTML_TEXT='''
<!DOCTYPE html> 
<html> 

<head>
    <title>Hello World!</title>
</head>

<body>
    <h1 style=\"color:green;\">GeeksforGeeks</h1>
    <form method="post" enctype="multipart/form-data">
        <label for="imageUpload">Choose an image to upload:</label>
        <input type="file" id="imageUpload" name="image" accept="image/*">
        <input type="submit" value="Upload Image">
    </form>
</body>

</html>
'''

class WebRequestHandler(BaseHTTPRequestHandler):
    @cached_property
    def url(self):
        return urlparse(self.path)

    @cached_property
    def query_data(self):
        return dict(parse_qsl(self.url.query))

    @cached_property
    def post_data(self):
        content_length = int(self.headers.get("Content-Length", 0))
        return self.rfile.read(content_length)

    @cached_property
    def form_data(self):
        return dict(parse_qsl(self.post_data.decode("utf-8")))

    @cached_property
    def cookies(self):
        return SimpleCookie(self.headers.get("Cookie"))

    def do_GET(self):
        #initial page
        self.send_response(200)
        #self.send_header("Content-Type", "application/json")
        self.send_header("Content-type", "text/html")
        self.end_headers()

        #self.wfile.write(self.get_response().encode("utf-8"))
        # Some custom HTML code, possibly generated by another function
        html = HTML_TEXT

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))

    def do_POST(self):
        #very basic system. http get is the html start up page
        #http post is when the user upload a file

        self.send_response(200)
        #self.send_header("Content-Type", "application/json")
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.path = '/upload'
        content_length = int(self.headers['Content-Length'])

        # get data content bytes
        file_content = self.rfile.read(content_length)

        # Use multipart parser to strip boundary
        multipart_data = decoder.MultipartDecoder(file_content, self.headers['Content-Type']).parts
        image_byte = multipart_data[0].content
        # Read image using cv2
        image_numpy = np.frombuffer(image_byte, np.int8)
        #TODO make it black and white ?
        img = cv2.imdecode(image_numpy, cv2.IMREAD_UNCHANGED)

        # Some custom HTML code, possibly generated by another function
        html = f"<html><head></head><body><h1>image {content_length} bytes received </h1></body></html>"

        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(html, "utf8"))



# Press the green button in the gutter to run the script.
def run(port=8080):
    logging.basicConfig(level=logging.INFO)

    # Create an object of the above class
    #handler_object = MyHttpRequestHandler
    handler_object = WebRequestHandler
    my_server = socketserver.TCPServer(("", port), handler_object)
    logging.info('Starting httpd...\n')
    # Star the server
    try:
        my_server.serve_forever()
    except KeyboardInterrupt:
        my_server.server_close()
        logging.info('Stopping httpd...\n')


if __name__ == '__main__':
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
